### ISSUE TITLE
About "No computer print-out is accepted" in the third line of homework #3

### ISSUE THREAD

**Issue by cmhsia** [NCTU-CSE-Introduction-to-Algorithms/Homework-Discuss#1]
Hi, I'd like to know whether we can **_print out the "Questions"_**, and **_answer_** the questions (on the print-out question sheet) **_in hand-writing_**?
Thank you.

**Comment by pvnr0082t** [comment]
Of course. You can do that. Just make sure your answer is in handwriting.
